/** Canonical scopes that may be granted to organization API tokens. */
export const canonicalApiTokenScopes = [
  "organization:read",
  "organization:write",
  "inference:read",
  "inference:write",
  "inference:invoke",
  "agents:read",
  "agents:write",
  "sessions:read",
  "sessions:write",
  "tools:read",
  "tools:write"
] as const;

/** Protected route actions intentionally available to API tokens. */
export const canonicalApiTokenActionScopes = {
  listOrganizationMembers: "organization:read",
  listOrganizationInvites: "organization:read",
  updateOrganizationMemberRole: "organization:write",
  removeOrganizationMember: "organization:write",
  createOrganizationInvite: "organization:write",
  fetchInferenceConfig: "inference:read",
  listOpenAICompatibleModels: "inference:read",
  retrieveOpenAICompatibleModel: "inference:read",
  createInferenceProvider: "inference:write",
  updateInferenceProvider: "inference:write",
  refreshInferenceProviderModels: "inference:write",
  updateInferenceModel: "inference:write",
  deleteInferenceProvider: "inference:write",
  updateInferenceModelDefault: "inference:write",
  createOpenAICompatibleChatCompletion: "inference:invoke",
  createOpenAICompatibleResponse: "inference:invoke",
  createOpenAICompatibleEmbedding: "inference:invoke",
  fetchAgentRun: "agents:read",
  streamAgentRunEvents: "agents:read",
  streamAgentChat: "agents:write",
  streamAgentPrompt: "agents:write",
  createAgentRun: "agents:write",
  cancelAgentRun: "agents:write",
  listProjects: "sessions:read",
  fetchProjectById: "sessions:read",
  listSessions: "sessions:read",
  fetchSessionById: "sessions:read",
  fetchSessionSettings: "sessions:read",
  createProject: "sessions:write",
  updateProject: "sessions:write",
  deleteProject: "sessions:write",
  addProjectContext: "sessions:write",
  deleteProjectContext: "sessions:write",
  createSession: "sessions:write",
  updateSession: "sessions:write",
  appendSessionMessage: "sessions:write",
  appendSessionState: "sessions:write",
  truncateSession: "sessions:write",
  archiveSession: "sessions:write",
  updateSessionSettings: "sessions:write",
  getToolGatewaySettings: "tools:read",
  listToolConnections: "tools:read",
  listToolDefinitions: "tools:read",
  updateToolGatewaySettings: "tools:write",
  createToolConnection: "tools:write",
  updateToolConnection: "tools:write",
  deleteToolConnection: "tools:write",
  updateToolDefinition: "tools:write",
  discoverToolCatalog: "tools:write",
  acknowledgeToolCatalog: "tools:write",
  invokeTool: "tools:write",
  decideToolApproval: "tools:write"
} as const;
