// Generated by services/api/scripts/generate-client.ts.
// Do not edit by hand.

export type UserRole = "admin" | "user";
export type OrganizationInviteStatus = "pending" | "accepted" | "declined";

export type RegisterAccountRequest = {
  email: string;
  password: string;
  displayName?: string;
  organizationName?: string;
};

export type EmailVerificationRequired = {
  emailVerificationRequired: true;
  email: string;
};

export type LoginRequest = {
  email: string;
  password: string;
  organizationId?: string;
};

export type VerifyEmailRequest = {
  token: string;
};

export type RequestPasswordResetRequest = {
  email: string;
};

export type ResetPasswordRequest = {
  token: string;
  password: string;
};

export type AuthActionResponse = { ok: true };

export type LogoutRequest = Record<string, never>;
export type RefreshSessionRequest = Record<string, never>;
export type LogoutAllSessionsRequest = Record<string, never>;
export type AuthRefreshReason =
  | "claims_changed"
  | "membership_changed"
  | "organization_changed"
  | "session_revoked";

export type ClientEvent = {
  type: "auth.refresh_required";
  reason: AuthRefreshReason;
};

export type UpdateCurrentUserRequest = {
  displayName: string;
};

export type UpdateCurrentOrganizationRequest = {
  name: string;
};

export type OrganizationSummary = {
  id: string;
  name: string;
  role: UserRole;
};

export type ListOrganizationsResponse = {
  activeOrganizationId: string | null;
  organizations: OrganizationSummary[];
};

export type SwitchOrganizationRequest = {
  organizationId: string;
};

export type CreateOrganizationRequest = {
  name: string;
};

export type DeleteCurrentOrganizationRequest = Record<string, never>;

export type DeleteCurrentOrganizationResponse =
  | {
      requiresOrganization: false;
      nextSession: AccessSession;
    }
  | {
      requiresOrganization: true;
      nextSession: AccessSession;
    };

export type OrganizationMember = {
  membershipId: string;
  userId: string;
  email: string;
  displayName: string;
  role: UserRole;
};

export type ListOrganizationMembersResponse = {
  members: OrganizationMember[];
};

export type UpdateOrganizationMemberRoleRequest = {
  membershipId: string;
  role: UserRole;
};

export type RemoveOrganizationMemberRequest = {
  membershipId: string;
};

export type CreateOrganizationInviteRequest = {
  email: string;
  role: UserRole;
  expiresInDays?: number;
};

export type OrganizationInvite = {
  id: string;
  email: string;
  role: UserRole;
  status: OrganizationInviteStatus;
  invitedByUserId: string | null;
  createdAt: string;
  expiresAt: string;
  respondedAt: string | null;
};

export type CreateOrganizationInviteResponse = {
  invite: OrganizationInvite;
};

export type ListOrganizationInvitesResponse = {
  invites: OrganizationInvite[];
};

export type RespondToOrganizationInviteRequest = {
  token: string;
  response: "accepted" | "declined";
};

export type RespondToOrganizationInviteResponse = {
  invite: OrganizationInvite;
  organization: {
    id: string;
    name: string;
  };
};

export type CurrentSession = {
  sessionId: string;
  user: {
    id: string;
    email: string;
    emailVerified: boolean;
    displayName: string;
  };
  organization: {
    id: string;
    name: string;
  } | null;
  membership: {
    id: string;
    role: UserRole;
  } | null;
  createdAt: string;
  expiresAt: string;
};

export type AccessSession = {
  accessToken: string;
  accessTokenExpiresAt: string;
  session: CurrentSession;
};

export type RegisterAccountResponse = EmailVerificationRequired;



export type WorkspaceMode = "chat" | "code" | "work" | "agents";

export type ModelDefaults = Record<WorkspaceMode, string>;

export type InferenceProviderKind =
  | "baseten"
  | "fireworks"
  | "anthropic"
  | "openai"
  | "openai-compatible";

export type InferenceModelInterface =
  | "chat-completions"
  | "messages"
  | "responses"
  | "embeddings";

export type InferenceModelInputModality =
  | "text"
  | "image"
  | "audio"
  | "video"
  | "pdf";

export type InferenceModelOutputModality =
  | "text"
  | "image"
  | "audio"
  | "embedding";

export type InferenceModelFeature =
  | "tools"
  | "structured-output"
  | "reasoning"
  | "citations"
  | "code-execution"
  | "batch";

export type InferenceModelCapabilities = {
  interfaces?: InferenceModelInterface[];
  inputModalities?: InferenceModelInputModality[];
  outputModalities?: InferenceModelOutputModality[];
  features?: InferenceModelFeature[];
};

export type InferenceModelStatus = {
  id: string;
  label: string;
  capabilities: InferenceModelCapabilities;
  enabled: boolean;
};

export type InferenceProviderStatus = {
  id: string;
  kind: InferenceProviderKind;
  label: string;
  configured: boolean;
  enabled: boolean;
  baseUrl: string;
  models: InferenceModelStatus[];
};

export type InferenceConfig = {
  organizationId: string;
  modelDefaults: ModelDefaults;
  providers: InferenceProviderStatus[];
};

export type AddInferenceProviderRequest = {
  kind: InferenceProviderKind;
  label: string;
  apiKey: string;
  baseUrl?: string;
};

export type UpdateInferenceProviderRequest = {
  providerId: string;
  enabled: boolean;
};

export type RefreshInferenceProviderModelsRequest = {
  providerId: string;
};

export type UpdateInferenceModelRequest = {
  providerId: string;
  modelId: string;
  enabled: boolean;
};

export type DeleteInferenceProviderRequest = {
  providerId: string;
};

export type UpdateInferenceModelDefaultRequest = {
  mode: WorkspaceMode;
  modelSelection: string;
};



export type SessionMessageRole = "user" | "assistant" | "system" | "tool";

export type SessionSummary = {
  id: string;
  organizationId: string;
  ownerUserId: string;
  title: string;
  agentId: string;
  projectId: string | null;
  pinnedAt: string | null;
  stateBytes: number;
  version: number;
  createdAt: string;
  updatedAt: string;
  archivedAt: string | null;
};

export type SessionMessage = {
  id: string;
  sessionId: string;
  role: SessionMessageRole;
  content: string;
  metadata: unknown;
  tokenCount: number | null;
  byteSize: number;
  createdAt: string;
};

export type SessionStateSnapshot = {
  id: string;
  sessionId: string;
  kind: string;
  state: unknown;
  byteSize: number;
  createdAt: string;
};

export type Session = SessionSummary & {
  messages: SessionMessage[];
  stateSnapshots: SessionStateSnapshot[];
};

export type ListSessionsResponse = {
  sessions: SessionSummary[];
};

export type CreateSessionRequest = {
  title?: string;
  agentId: string;
  projectId?: string | null;
};

export type UpdateSessionRequest = {
  title?: string;
  projectId?: string | null;
  pinned?: boolean;
};

export type ProjectSummary = {
  id: string;
  organizationId: string;
  ownerUserId: string;
  name: string;
  instructions: string;
  memory: string;
  pinnedAt: string | null;
  createdAt: string;
  updatedAt: string;
};

export type ProjectContextItem = {
  id: string;
  projectId: string;
  filename: string;
  mediaType: string;
  content: string;
  byteSize: number;
  createdAt: string;
};

export type Project = ProjectSummary & {
  contextItems: ProjectContextItem[];
};

export type ListProjectsResponse = {
  projects: ProjectSummary[];
};

export type CreateProjectRequest = {
  name: string;
};

export type UpdateProjectRequest = {
  name?: string;
  instructions?: string;
  memory?: string;
  pinned?: boolean;
};

export type DeleteProjectRequest = Record<string, never>;

export type AddProjectContextRequest = {
  filename: string;
  mediaType: string;
  content: string;
};

export type DeleteProjectContextRequest = Record<string, never>;

export type AppendSessionMessageRequest = {
  role: SessionMessageRole;
  content: string;
  metadata?: unknown;
  tokenCount?: number | null;
};

export type AppendSessionStateRequest = {
  kind: string;
  state: unknown;
};

export type TruncateSessionRequest = {
  afterMessageId: string | null;
};

export type ArchiveSessionRequest = Record<string, never>;

export type SessionSettings = {
  organizationId: string;
  retentionSeconds: number;
  createdAt: string;
  updatedAt: string;
};

export type UpdateSessionSettingsRequest = {
  retentionSeconds: number;
};



export type AgentChatAttachment = {
  filename: string;
  mediaType: string;
  content: string;
};

export type AgentChatMessage = {
  role: "user" | "assistant";
  content: string;
  attachments?: AgentChatAttachment[];
};

export type AgentStreamEvent =
  | { type: "response-start" }
  | { type: "text-delta"; delta: string }
  | { type: "reasoning-delta"; delta: string }
  | {
      type: "tool-input";
      toolCallId: string;
      toolName: string;
      input: unknown;
    }
  | {
      type: "tool-output";
      toolCallId: string;
      toolName: string;
      output?: unknown;
      errorText?: string;
    }
  | { type: "source"; sourceId: string; url: string; title: string }
  | {
      type: "artifact";
      artifactId: string;
      title: string;
      description?: string;
      mediaType: string;
      content?: string;
      url?: string;
    }
  | { type: "response-complete" }
  | { type: "response-error"; message: string };

export type AgentChatRequest = {
  modelSelection: string;
  sessionId: string;
  messages: AgentChatMessage[];
};

export type AgentPromptRequest = {
  modelSelection: string;
  messages: AgentChatMessage[];
};

export const apiRoutes = [
  {
    "id": "registerAccount",
    "method": "POST",
    "path": "/v1beta/auth/register",
    "requestType": "RegisterAccountRequest",
    "responseType": "RegisterAccountResponse",
    "auth": false,
    "kind": "json"
  },
  {
    "id": "login",
    "method": "POST",
    "path": "/v1beta/auth/login",
    "requestType": "LoginRequest",
    "responseType": "AccessSession",
    "auth": false,
    "kind": "json"
  },
  {
    "id": "verifyEmail",
    "method": "POST",
    "path": "/v1beta/auth/verify-email",
    "requestType": "VerifyEmailRequest",
    "responseType": "AuthActionResponse",
    "auth": false,
    "kind": "json"
  },
  {
    "id": "requestPasswordReset",
    "method": "POST",
    "path": "/v1beta/auth/password-reset/request",
    "requestType": "RequestPasswordResetRequest",
    "responseType": "AuthActionResponse",
    "auth": false,
    "kind": "json"
  },
  {
    "id": "resetPassword",
    "method": "POST",
    "path": "/v1beta/auth/password-reset",
    "requestType": "ResetPasswordRequest",
    "responseType": "AuthActionResponse",
    "auth": false,
    "kind": "json"
  },
  {
    "id": "refreshSession",
    "method": "POST",
    "path": "/v1beta/auth/refresh",
    "requestType": "RefreshSessionRequest",
    "responseType": "AccessSession",
    "auth": false,
    "kind": "json"
  },
  {
    "id": "logout",
    "method": "POST",
    "path": "/v1beta/auth/logout",
    "requestType": "LogoutRequest",
    "responseType": "{ ok: true }",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "logoutAllSessions",
    "method": "POST",
    "path": "/v1beta/auth/logout-all",
    "requestType": "LogoutAllSessionsRequest",
    "responseType": "{ ok: true }",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "fetchSession",
    "method": "GET",
    "path": "/v1beta/session",
    "responseType": "CurrentSession",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "openClientEvents",
    "method": "GET",
    "path": "/v1beta/auth/events",
    "responseType": "ClientEvent",
    "auth": true,
    "kind": "event-stream"
  },
  {
    "id": "listOrganizations",
    "method": "GET",
    "path": "/v1beta/organizations",
    "responseType": "ListOrganizationsResponse",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "switchOrganization",
    "method": "POST",
    "path": "/v1beta/organizations/switch",
    "requestType": "SwitchOrganizationRequest",
    "responseType": "AccessSession",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "createOrganization",
    "method": "POST",
    "path": "/v1beta/organizations",
    "requestType": "CreateOrganizationRequest",
    "responseType": "AccessSession",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "updateCurrentUser",
    "method": "POST",
    "path": "/v1beta/session/user",
    "requestType": "UpdateCurrentUserRequest",
    "responseType": "CurrentSession",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "updateCurrentOrganization",
    "method": "POST",
    "path": "/v1beta/session/organization",
    "requestType": "UpdateCurrentOrganizationRequest",
    "responseType": "CurrentSession",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "deleteCurrentOrganization",
    "method": "POST",
    "path": "/v1beta/session/organization/delete",
    "requestType": "DeleteCurrentOrganizationRequest",
    "responseType": "DeleteCurrentOrganizationResponse",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "listOrganizationMembers",
    "method": "GET",
    "path": "/v1beta/session/organization/members",
    "responseType": "ListOrganizationMembersResponse",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "updateOrganizationMemberRole",
    "method": "POST",
    "path": "/v1beta/session/organization/members/role",
    "requestType": "UpdateOrganizationMemberRoleRequest",
    "responseType": "ListOrganizationMembersResponse",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "removeOrganizationMember",
    "method": "POST",
    "path": "/v1beta/session/organization/members/remove",
    "requestType": "RemoveOrganizationMemberRequest",
    "responseType": "ListOrganizationMembersResponse",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "createOrganizationInvite",
    "method": "POST",
    "path": "/v1beta/session/organization/invites",
    "requestType": "CreateOrganizationInviteRequest",
    "responseType": "CreateOrganizationInviteResponse",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "listOrganizationInvites",
    "method": "GET",
    "path": "/v1beta/session/organization/invites",
    "responseType": "ListOrganizationInvitesResponse",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "respondToOrganizationInvite",
    "method": "POST",
    "path": "/v1beta/session/organization/invites/respond",
    "requestType": "RespondToOrganizationInviteRequest",
    "responseType": "RespondToOrganizationInviteResponse",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "fetchInferenceConfig",
    "method": "GET",
    "path": "/v1beta/inference/config",
    "responseType": "InferenceConfig",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "createInferenceProvider",
    "method": "POST",
    "path": "/v1beta/inference/providers",
    "requestType": "AddInferenceProviderRequest",
    "responseType": "InferenceProviderStatus",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "updateInferenceProvider",
    "method": "POST",
    "path": "/v1beta/inference/providers/update",
    "requestType": "UpdateInferenceProviderRequest",
    "responseType": "InferenceConfig",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "refreshInferenceProviderModels",
    "method": "POST",
    "path": "/v1beta/inference/providers/refresh-models",
    "requestType": "RefreshInferenceProviderModelsRequest",
    "responseType": "InferenceConfig",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "updateInferenceModel",
    "method": "POST",
    "path": "/v1beta/inference/models/update",
    "requestType": "UpdateInferenceModelRequest",
    "responseType": "InferenceConfig",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "deleteInferenceProvider",
    "method": "POST",
    "path": "/v1beta/inference/providers/delete",
    "requestType": "DeleteInferenceProviderRequest",
    "responseType": "InferenceConfig",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "updateInferenceModelDefault",
    "method": "POST",
    "path": "/v1beta/inference/model-defaults/update",
    "requestType": "UpdateInferenceModelDefaultRequest",
    "responseType": "InferenceConfig",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "listProjects",
    "method": "GET",
    "path": "/v1beta/projects",
    "responseType": "ListProjectsResponse",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "createProject",
    "method": "POST",
    "path": "/v1beta/projects",
    "requestType": "CreateProjectRequest",
    "responseType": "Project",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "fetchProjectById",
    "method": "GET",
    "path": "/v1beta/projects/:projectId",
    "responseType": "Project",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "updateProject",
    "method": "PATCH",
    "path": "/v1beta/projects/:projectId",
    "requestType": "UpdateProjectRequest",
    "responseType": "Project",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "deleteProject",
    "method": "POST",
    "path": "/v1beta/projects/:projectId/delete",
    "requestType": "DeleteProjectRequest",
    "responseType": "ProjectSummary",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "addProjectContext",
    "method": "POST",
    "path": "/v1beta/projects/:projectId/context",
    "requestType": "AddProjectContextRequest",
    "responseType": "ProjectContextItem",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "deleteProjectContext",
    "method": "POST",
    "path": "/v1beta/projects/:projectId/context/:contextId/delete",
    "requestType": "DeleteProjectContextRequest",
    "responseType": "Project",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "listSessions",
    "method": "GET",
    "path": "/v1beta/sessions",
    "responseType": "ListSessionsResponse",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "createSession",
    "method": "POST",
    "path": "/v1beta/sessions",
    "requestType": "CreateSessionRequest",
    "responseType": "SessionSummary",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "fetchSessionById",
    "method": "GET",
    "path": "/v1beta/sessions/:sessionId",
    "responseType": "Session",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "updateSession",
    "method": "PATCH",
    "path": "/v1beta/sessions/:sessionId",
    "requestType": "UpdateSessionRequest",
    "responseType": "SessionSummary",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "appendSessionMessage",
    "method": "POST",
    "path": "/v1beta/sessions/:sessionId/messages",
    "requestType": "AppendSessionMessageRequest",
    "responseType": "SessionMessage",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "appendSessionState",
    "method": "POST",
    "path": "/v1beta/sessions/:sessionId/state",
    "requestType": "AppendSessionStateRequest",
    "responseType": "SessionStateSnapshot",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "truncateSession",
    "method": "POST",
    "path": "/v1beta/sessions/:sessionId/truncate",
    "requestType": "TruncateSessionRequest",
    "responseType": "Session",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "archiveSession",
    "method": "POST",
    "path": "/v1beta/sessions/:sessionId/archive",
    "requestType": "ArchiveSessionRequest",
    "responseType": "SessionSummary",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "fetchSessionSettings",
    "method": "GET",
    "path": "/v1beta/settings/sessions",
    "responseType": "SessionSettings",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "updateSessionSettings",
    "method": "PATCH",
    "path": "/v1beta/settings/sessions",
    "requestType": "UpdateSessionSettingsRequest",
    "responseType": "SessionSettings",
    "auth": true,
    "kind": "json"
  },
  {
    "id": "streamAgentChat",
    "method": "POST",
    "path": "/v1beta/agents/:agentSlug/chat",
    "requestType": "AgentChatRequest",
    "responseType": "Response",
    "auth": true,
    "kind": "stream"
  },
  {
    "id": "streamAgentPrompt",
    "method": "POST",
    "path": "/v1beta/agents/:agentSlug/prompt",
    "requestType": "AgentPromptRequest",
    "responseType": "Response",
    "auth": true,
    "kind": "stream"
  }
] as const;

const REGISTER_ACCOUNT_ROUTE = apiRoutes.find((route) => route.id === "registerAccount")!;
const LOGIN_ROUTE = apiRoutes.find((route) => route.id === "login")!;
const VERIFY_EMAIL_ROUTE = apiRoutes.find((route) => route.id === "verifyEmail")!;
const REQUEST_PASSWORD_RESET_ROUTE = apiRoutes.find((route) => route.id === "requestPasswordReset")!;
const RESET_PASSWORD_ROUTE = apiRoutes.find((route) => route.id === "resetPassword")!;
const REFRESH_SESSION_ROUTE = apiRoutes.find((route) => route.id === "refreshSession")!;
const LOGOUT_ROUTE = apiRoutes.find((route) => route.id === "logout")!;
const LOGOUT_ALL_SESSIONS_ROUTE = apiRoutes.find((route) => route.id === "logoutAllSessions")!;
const FETCH_SESSION_ROUTE = apiRoutes.find((route) => route.id === "fetchSession")!;
const OPEN_CLIENT_EVENTS_ROUTE = apiRoutes.find((route) => route.id === "openClientEvents")!;
const LIST_ORGANIZATIONS_ROUTE = apiRoutes.find((route) => route.id === "listOrganizations")!;
const SWITCH_ORGANIZATION_ROUTE = apiRoutes.find((route) => route.id === "switchOrganization")!;
const CREATE_ORGANIZATION_ROUTE = apiRoutes.find((route) => route.id === "createOrganization")!;
const UPDATE_CURRENT_USER_ROUTE = apiRoutes.find((route) => route.id === "updateCurrentUser")!;
const UPDATE_CURRENT_ORGANIZATION_ROUTE = apiRoutes.find((route) => route.id === "updateCurrentOrganization")!;
const DELETE_CURRENT_ORGANIZATION_ROUTE = apiRoutes.find((route) => route.id === "deleteCurrentOrganization")!;
const LIST_ORGANIZATION_MEMBERS_ROUTE = apiRoutes.find((route) => route.id === "listOrganizationMembers")!;
const UPDATE_ORGANIZATION_MEMBER_ROLE_ROUTE = apiRoutes.find((route) => route.id === "updateOrganizationMemberRole")!;
const REMOVE_ORGANIZATION_MEMBER_ROUTE = apiRoutes.find((route) => route.id === "removeOrganizationMember")!;
const CREATE_ORGANIZATION_INVITE_ROUTE = apiRoutes.find((route) => route.id === "createOrganizationInvite")!;
const LIST_ORGANIZATION_INVITES_ROUTE = apiRoutes.find((route) => route.id === "listOrganizationInvites")!;
const RESPOND_TO_ORGANIZATION_INVITE_ROUTE = apiRoutes.find((route) => route.id === "respondToOrganizationInvite")!;
const FETCH_INFERENCE_CONFIG_ROUTE = apiRoutes.find((route) => route.id === "fetchInferenceConfig")!;
const CREATE_INFERENCE_PROVIDER_ROUTE = apiRoutes.find((route) => route.id === "createInferenceProvider")!;
const UPDATE_INFERENCE_PROVIDER_ROUTE = apiRoutes.find((route) => route.id === "updateInferenceProvider")!;
const REFRESH_INFERENCE_PROVIDER_MODELS_ROUTE = apiRoutes.find((route) => route.id === "refreshInferenceProviderModels")!;
const UPDATE_INFERENCE_MODEL_ROUTE = apiRoutes.find((route) => route.id === "updateInferenceModel")!;
const DELETE_INFERENCE_PROVIDER_ROUTE = apiRoutes.find((route) => route.id === "deleteInferenceProvider")!;
const UPDATE_INFERENCE_MODEL_DEFAULT_ROUTE = apiRoutes.find((route) => route.id === "updateInferenceModelDefault")!;
const LIST_PROJECTS_ROUTE = apiRoutes.find((route) => route.id === "listProjects")!;
const CREATE_PROJECT_ROUTE = apiRoutes.find((route) => route.id === "createProject")!;
const FETCH_PROJECT_BY_ID_ROUTE = apiRoutes.find((route) => route.id === "fetchProjectById")!;
const UPDATE_PROJECT_ROUTE = apiRoutes.find((route) => route.id === "updateProject")!;
const DELETE_PROJECT_ROUTE = apiRoutes.find((route) => route.id === "deleteProject")!;
const ADD_PROJECT_CONTEXT_ROUTE = apiRoutes.find((route) => route.id === "addProjectContext")!;
const DELETE_PROJECT_CONTEXT_ROUTE = apiRoutes.find((route) => route.id === "deleteProjectContext")!;
const LIST_SESSIONS_ROUTE = apiRoutes.find((route) => route.id === "listSessions")!;
const CREATE_SESSION_ROUTE = apiRoutes.find((route) => route.id === "createSession")!;
const FETCH_SESSION_BY_ID_ROUTE = apiRoutes.find((route) => route.id === "fetchSessionById")!;
const UPDATE_SESSION_ROUTE = apiRoutes.find((route) => route.id === "updateSession")!;
const APPEND_SESSION_MESSAGE_ROUTE = apiRoutes.find((route) => route.id === "appendSessionMessage")!;
const APPEND_SESSION_STATE_ROUTE = apiRoutes.find((route) => route.id === "appendSessionState")!;
const TRUNCATE_SESSION_ROUTE = apiRoutes.find((route) => route.id === "truncateSession")!;
const ARCHIVE_SESSION_ROUTE = apiRoutes.find((route) => route.id === "archiveSession")!;
const FETCH_SESSION_SETTINGS_ROUTE = apiRoutes.find((route) => route.id === "fetchSessionSettings")!;
const UPDATE_SESSION_SETTINGS_ROUTE = apiRoutes.find((route) => route.id === "updateSessionSettings")!;
const STREAM_AGENT_CHAT_ROUTE = apiRoutes.find((route) => route.id === "streamAgentChat")!;
const STREAM_AGENT_PROMPT_ROUTE = apiRoutes.find((route) => route.id === "streamAgentPrompt")!;

export function resolveApiBaseUrl(apiBaseUrl: string) {
  return apiBaseUrl.trim().replace(/\/+$/, "");
}

export function apiUrl(apiBaseUrl: string, path: string) {
  return `${resolveApiBaseUrl(apiBaseUrl)}${path}`;
}

export function routePath(path: string, params: Record<string, string>) {
  return path.replace(/:([A-Za-z0-9_]+)/g, (_match, key: string) => {
    const value = params[key];
    if (!value) {
      throw new Error(`Missing API route parameter: ${key}`);
    }

    return encodeURIComponent(value);
  });
}

export class ApiError extends Error {
  constructor(
    readonly routeId: string,
    readonly status: number,
    readonly details: string,
    message: string
  ) {
    super(message);
  }
}

async function apiError(routeId: string, response: Response) {
  const details = await response.text().catch(() => "");
  const message = parseErrorMessage(details);
  return new ApiError(
    routeId,
    response.status,
    details,
    `${routeId} failed with ${response.status}${message ? `: ${message}` : ""}`
  );
}

function parseErrorMessage(details: string) {
  if (!details) {
    return "";
  }

  try {
    const body = JSON.parse(details) as { error?: unknown; message?: unknown };
    if (typeof body.message === "string" && body.message) {
      return body.message;
    }

    if (typeof body.error === "string" && body.error) {
      return body.error;
    }
  } catch {
    return details;
  }

  return details;
}

function authorizationHeaders(sessionToken: string | undefined): Record<string, string> {
  return sessionToken ? { authorization: `Bearer ${sessionToken}` } : {};
}

export async function registerAccount(
  apiBaseUrl: string,
  body: RegisterAccountRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, REGISTER_ACCOUNT_ROUTE.path), {
    method: "POST",
    credentials: "include",
    headers: {
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("registerAccount", response);
  }

  return response.json() as Promise<RegisterAccountResponse>;
}

export async function login(
  apiBaseUrl: string,
  body: LoginRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, LOGIN_ROUTE.path), {
    method: "POST",
    credentials: "include",
    headers: {
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("login", response);
  }

  return response.json() as Promise<AccessSession>;
}

export async function verifyEmail(
  apiBaseUrl: string,
  body: VerifyEmailRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, VERIFY_EMAIL_ROUTE.path), {
    method: "POST",
    credentials: "include",
    headers: {
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("verifyEmail", response);
  }

  return response.json() as Promise<AuthActionResponse>;
}

export async function requestPasswordReset(
  apiBaseUrl: string,
  body: RequestPasswordResetRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, REQUEST_PASSWORD_RESET_ROUTE.path), {
    method: "POST",
    credentials: "include",
    headers: {
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("requestPasswordReset", response);
  }

  return response.json() as Promise<AuthActionResponse>;
}

export async function resetPassword(
  apiBaseUrl: string,
  body: ResetPasswordRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, RESET_PASSWORD_ROUTE.path), {
    method: "POST",
    credentials: "include",
    headers: {
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("resetPassword", response);
  }

  return response.json() as Promise<AuthActionResponse>;
}

export async function refreshSession(
  apiBaseUrl: string,
  body: RefreshSessionRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, REFRESH_SESSION_ROUTE.path), {
    method: "POST",
    credentials: "include",
    headers: {
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("refreshSession", response);
  }

  return response.json() as Promise<AccessSession>;
}

export async function logout(
  apiBaseUrl: string,
  sessionToken: string | undefined, body: LogoutRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, LOGOUT_ROUTE.path), {
    method: "POST",
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("logout", response);
  }

  return response.json() as Promise<{ ok: true }>;
}

export async function logoutAllSessions(
  apiBaseUrl: string,
  sessionToken: string | undefined, body: LogoutAllSessionsRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, LOGOUT_ALL_SESSIONS_ROUTE.path), {
    method: "POST",
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("logoutAllSessions", response);
  }

  return response.json() as Promise<{ ok: true }>;
}

export async function fetchSession(
  apiBaseUrl: string,
  sessionToken: string | undefined,
) {
  const response = await fetch(apiUrl(apiBaseUrl, FETCH_SESSION_ROUTE.path), {
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),

    }
  });

  if (!response.ok) {
    throw await apiError("fetchSession", response);
  }

  return response.json() as Promise<CurrentSession>;
}

export function openClientEvents(
  apiBaseUrl: string,
  sessionToken: string | undefined, signal?: AbortSignal
) {
  return fetch(apiUrl(apiBaseUrl, OPEN_CLIENT_EVENTS_ROUTE.path), {
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),
      accept: "text/event-stream"
    },
    signal
  });
}

export async function listOrganizations(
  apiBaseUrl: string,
  sessionToken: string | undefined,
) {
  const response = await fetch(apiUrl(apiBaseUrl, LIST_ORGANIZATIONS_ROUTE.path), {
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),

    }
  });

  if (!response.ok) {
    throw await apiError("listOrganizations", response);
  }

  return response.json() as Promise<ListOrganizationsResponse>;
}

export async function switchOrganization(
  apiBaseUrl: string,
  sessionToken: string | undefined, body: SwitchOrganizationRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, SWITCH_ORGANIZATION_ROUTE.path), {
    method: "POST",
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("switchOrganization", response);
  }

  return response.json() as Promise<AccessSession>;
}

export async function createOrganization(
  apiBaseUrl: string,
  sessionToken: string | undefined, body: CreateOrganizationRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, CREATE_ORGANIZATION_ROUTE.path), {
    method: "POST",
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("createOrganization", response);
  }

  return response.json() as Promise<AccessSession>;
}

export async function updateCurrentUser(
  apiBaseUrl: string,
  sessionToken: string | undefined, body: UpdateCurrentUserRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, UPDATE_CURRENT_USER_ROUTE.path), {
    method: "POST",
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("updateCurrentUser", response);
  }

  return response.json() as Promise<CurrentSession>;
}

export async function updateCurrentOrganization(
  apiBaseUrl: string,
  sessionToken: string | undefined, body: UpdateCurrentOrganizationRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, UPDATE_CURRENT_ORGANIZATION_ROUTE.path), {
    method: "POST",
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("updateCurrentOrganization", response);
  }

  return response.json() as Promise<CurrentSession>;
}

export async function deleteCurrentOrganization(
  apiBaseUrl: string,
  sessionToken: string | undefined, body: DeleteCurrentOrganizationRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, DELETE_CURRENT_ORGANIZATION_ROUTE.path), {
    method: "POST",
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("deleteCurrentOrganization", response);
  }

  return response.json() as Promise<DeleteCurrentOrganizationResponse>;
}

export async function listOrganizationMembers(
  apiBaseUrl: string,
  sessionToken: string | undefined,
) {
  const response = await fetch(apiUrl(apiBaseUrl, LIST_ORGANIZATION_MEMBERS_ROUTE.path), {
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),

    }
  });

  if (!response.ok) {
    throw await apiError("listOrganizationMembers", response);
  }

  return response.json() as Promise<ListOrganizationMembersResponse>;
}

export async function updateOrganizationMemberRole(
  apiBaseUrl: string,
  sessionToken: string | undefined, body: UpdateOrganizationMemberRoleRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, UPDATE_ORGANIZATION_MEMBER_ROLE_ROUTE.path), {
    method: "POST",
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("updateOrganizationMemberRole", response);
  }

  return response.json() as Promise<ListOrganizationMembersResponse>;
}

export async function removeOrganizationMember(
  apiBaseUrl: string,
  sessionToken: string | undefined, body: RemoveOrganizationMemberRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, REMOVE_ORGANIZATION_MEMBER_ROUTE.path), {
    method: "POST",
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("removeOrganizationMember", response);
  }

  return response.json() as Promise<ListOrganizationMembersResponse>;
}

export async function createOrganizationInvite(
  apiBaseUrl: string,
  sessionToken: string | undefined, body: CreateOrganizationInviteRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, CREATE_ORGANIZATION_INVITE_ROUTE.path), {
    method: "POST",
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("createOrganizationInvite", response);
  }

  return response.json() as Promise<CreateOrganizationInviteResponse>;
}

export async function listOrganizationInvites(
  apiBaseUrl: string,
  sessionToken: string | undefined,
) {
  const response = await fetch(apiUrl(apiBaseUrl, LIST_ORGANIZATION_INVITES_ROUTE.path), {
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),

    }
  });

  if (!response.ok) {
    throw await apiError("listOrganizationInvites", response);
  }

  return response.json() as Promise<ListOrganizationInvitesResponse>;
}

export async function respondToOrganizationInvite(
  apiBaseUrl: string,
  sessionToken: string | undefined, body: RespondToOrganizationInviteRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, RESPOND_TO_ORGANIZATION_INVITE_ROUTE.path), {
    method: "POST",
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("respondToOrganizationInvite", response);
  }

  return response.json() as Promise<RespondToOrganizationInviteResponse>;
}

export async function fetchInferenceConfig(
  apiBaseUrl: string,
  sessionToken: string | undefined,
) {
  const response = await fetch(apiUrl(apiBaseUrl, FETCH_INFERENCE_CONFIG_ROUTE.path), {
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),

    }
  });

  if (!response.ok) {
    throw await apiError("fetchInferenceConfig", response);
  }

  return response.json() as Promise<InferenceConfig>;
}

export async function createInferenceProvider(
  apiBaseUrl: string,
  sessionToken: string | undefined, body: AddInferenceProviderRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, CREATE_INFERENCE_PROVIDER_ROUTE.path), {
    method: "POST",
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("createInferenceProvider", response);
  }

  return response.json() as Promise<InferenceProviderStatus>;
}

export async function updateInferenceProvider(
  apiBaseUrl: string,
  sessionToken: string | undefined, body: UpdateInferenceProviderRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, UPDATE_INFERENCE_PROVIDER_ROUTE.path), {
    method: "POST",
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("updateInferenceProvider", response);
  }

  return response.json() as Promise<InferenceConfig>;
}

export async function refreshInferenceProviderModels(
  apiBaseUrl: string,
  sessionToken: string | undefined, body: RefreshInferenceProviderModelsRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, REFRESH_INFERENCE_PROVIDER_MODELS_ROUTE.path), {
    method: "POST",
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("refreshInferenceProviderModels", response);
  }

  return response.json() as Promise<InferenceConfig>;
}

export async function updateInferenceModel(
  apiBaseUrl: string,
  sessionToken: string | undefined, body: UpdateInferenceModelRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, UPDATE_INFERENCE_MODEL_ROUTE.path), {
    method: "POST",
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("updateInferenceModel", response);
  }

  return response.json() as Promise<InferenceConfig>;
}

export async function deleteInferenceProvider(
  apiBaseUrl: string,
  sessionToken: string | undefined, body: DeleteInferenceProviderRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, DELETE_INFERENCE_PROVIDER_ROUTE.path), {
    method: "POST",
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("deleteInferenceProvider", response);
  }

  return response.json() as Promise<InferenceConfig>;
}

export async function updateInferenceModelDefault(
  apiBaseUrl: string,
  sessionToken: string | undefined, body: UpdateInferenceModelDefaultRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, UPDATE_INFERENCE_MODEL_DEFAULT_ROUTE.path), {
    method: "POST",
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("updateInferenceModelDefault", response);
  }

  return response.json() as Promise<InferenceConfig>;
}

export async function listProjects(
  apiBaseUrl: string,
  sessionToken: string | undefined,
) {
  const response = await fetch(apiUrl(apiBaseUrl, LIST_PROJECTS_ROUTE.path), {
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),

    }
  });

  if (!response.ok) {
    throw await apiError("listProjects", response);
  }

  return response.json() as Promise<ListProjectsResponse>;
}

export async function createProject(
  apiBaseUrl: string,
  sessionToken: string | undefined, body: CreateProjectRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, CREATE_PROJECT_ROUTE.path), {
    method: "POST",
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("createProject", response);
  }

  return response.json() as Promise<Project>;
}

export async function fetchProjectById(
  apiBaseUrl: string,
  projectId: string,
  sessionToken: string | undefined,
) {
  const response = await fetch(apiUrl(apiBaseUrl, routePath(FETCH_PROJECT_BY_ID_ROUTE.path, { projectId })), {
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),

    }
  });

  if (!response.ok) {
    throw await apiError("fetchProjectById", response);
  }

  return response.json() as Promise<Project>;
}

export async function updateProject(
  apiBaseUrl: string,
  projectId: string,
  sessionToken: string | undefined, body: UpdateProjectRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, routePath(UPDATE_PROJECT_ROUTE.path, { projectId })), {
    method: "PATCH",
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("updateProject", response);
  }

  return response.json() as Promise<Project>;
}

export async function deleteProject(
  apiBaseUrl: string,
  projectId: string,
  sessionToken: string | undefined, body: DeleteProjectRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, routePath(DELETE_PROJECT_ROUTE.path, { projectId })), {
    method: "POST",
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("deleteProject", response);
  }

  return response.json() as Promise<ProjectSummary>;
}

export async function addProjectContext(
  apiBaseUrl: string,
  projectId: string,
  sessionToken: string | undefined, body: AddProjectContextRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, routePath(ADD_PROJECT_CONTEXT_ROUTE.path, { projectId })), {
    method: "POST",
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("addProjectContext", response);
  }

  return response.json() as Promise<ProjectContextItem>;
}

export async function deleteProjectContext(
  apiBaseUrl: string,
  projectId: string, contextId: string,
  sessionToken: string | undefined, body: DeleteProjectContextRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, routePath(DELETE_PROJECT_CONTEXT_ROUTE.path, { projectId, contextId })), {
    method: "POST",
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("deleteProjectContext", response);
  }

  return response.json() as Promise<Project>;
}

export async function listSessions(
  apiBaseUrl: string,
  sessionToken: string | undefined,
) {
  const response = await fetch(apiUrl(apiBaseUrl, LIST_SESSIONS_ROUTE.path), {
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),

    }
  });

  if (!response.ok) {
    throw await apiError("listSessions", response);
  }

  return response.json() as Promise<ListSessionsResponse>;
}

export async function createSession(
  apiBaseUrl: string,
  sessionToken: string | undefined, body: CreateSessionRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, CREATE_SESSION_ROUTE.path), {
    method: "POST",
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("createSession", response);
  }

  return response.json() as Promise<SessionSummary>;
}

export async function fetchSessionById(
  apiBaseUrl: string,
  sessionId: string,
  sessionToken: string | undefined,
) {
  const response = await fetch(apiUrl(apiBaseUrl, routePath(FETCH_SESSION_BY_ID_ROUTE.path, { sessionId })), {
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),

    }
  });

  if (!response.ok) {
    throw await apiError("fetchSessionById", response);
  }

  return response.json() as Promise<Session>;
}

export async function updateSession(
  apiBaseUrl: string,
  sessionId: string,
  sessionToken: string | undefined, body: UpdateSessionRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, routePath(UPDATE_SESSION_ROUTE.path, { sessionId })), {
    method: "PATCH",
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("updateSession", response);
  }

  return response.json() as Promise<SessionSummary>;
}

export async function appendSessionMessage(
  apiBaseUrl: string,
  sessionId: string,
  sessionToken: string | undefined, body: AppendSessionMessageRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, routePath(APPEND_SESSION_MESSAGE_ROUTE.path, { sessionId })), {
    method: "POST",
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("appendSessionMessage", response);
  }

  return response.json() as Promise<SessionMessage>;
}

export async function appendSessionState(
  apiBaseUrl: string,
  sessionId: string,
  sessionToken: string | undefined, body: AppendSessionStateRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, routePath(APPEND_SESSION_STATE_ROUTE.path, { sessionId })), {
    method: "POST",
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("appendSessionState", response);
  }

  return response.json() as Promise<SessionStateSnapshot>;
}

export async function truncateSession(
  apiBaseUrl: string,
  sessionId: string,
  sessionToken: string | undefined, body: TruncateSessionRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, routePath(TRUNCATE_SESSION_ROUTE.path, { sessionId })), {
    method: "POST",
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("truncateSession", response);
  }

  return response.json() as Promise<Session>;
}

export async function archiveSession(
  apiBaseUrl: string,
  sessionId: string,
  sessionToken: string | undefined, body: ArchiveSessionRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, routePath(ARCHIVE_SESSION_ROUTE.path, { sessionId })), {
    method: "POST",
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("archiveSession", response);
  }

  return response.json() as Promise<SessionSummary>;
}

export async function fetchSessionSettings(
  apiBaseUrl: string,
  sessionToken: string | undefined,
) {
  const response = await fetch(apiUrl(apiBaseUrl, FETCH_SESSION_SETTINGS_ROUTE.path), {
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),

    }
  });

  if (!response.ok) {
    throw await apiError("fetchSessionSettings", response);
  }

  return response.json() as Promise<SessionSettings>;
}

export async function updateSessionSettings(
  apiBaseUrl: string,
  sessionToken: string | undefined, body: UpdateSessionSettingsRequest
) {
  const response = await fetch(apiUrl(apiBaseUrl, UPDATE_SESSION_SETTINGS_ROUTE.path), {
    method: "PATCH",
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),
      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError("updateSessionSettings", response);
  }

  return response.json() as Promise<SessionSettings>;
}

export function streamAgentChat(
  apiBaseUrl: string,
  agentSlug: string,
  sessionToken: string | undefined, body: AgentChatRequest,
  signal?: AbortSignal
) {
  return fetch(apiUrl(apiBaseUrl, routePath(STREAM_AGENT_CHAT_ROUTE.path, { agentSlug })), {
    method: "POST",
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),
      "content-type": "application/json"
    },
    body: JSON.stringify(body),
    signal
  });
}

export function streamAgentPrompt(
  apiBaseUrl: string,
  agentSlug: string,
  sessionToken: string | undefined, body: AgentPromptRequest,
  signal?: AbortSignal
) {
  return fetch(apiUrl(apiBaseUrl, routePath(STREAM_AGENT_PROMPT_ROUTE.path, { agentSlug })), {
    method: "POST",
    credentials: "include",
    headers: {
      ...authorizationHeaders(sessionToken),
      "content-type": "application/json"
    },
    body: JSON.stringify(body),
    signal
  });
}

