import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { apiSpec } from "../src/spec";

const outputPath = resolve(
  import.meta.dir,
  "../../../packages/api-client/src/generated.ts"
);

const routes = apiSpec.routes;

function routeConstantName(id: string) {
  return `${id.replace(/[A-Z]/g, (letter) => `_${letter}`).toUpperCase()}_ROUTE`;
}

function functionSource(route: (typeof routes)[number]) {
  const constantName = routeConstantName(route.id);
  const params = pathParams(route.path);
  const pathArguments = params.map((param) => `${param}: string`);
  const leadingPathArguments =
    pathArguments.length > 0 ? `${pathArguments.join(", ")},\n  ` : "";
  const authParameter = route.auth ? "sessionToken: string | undefined, " : "";
  const authHeaderLine = route.auth
    ? "      ...authorizationHeaders(sessionToken),\n"
    : "";
  const pathExpression =
    params.length > 0
      ? `routePath(${constantName}.path, { ${params.join(", ")} })`
      : `${constantName}.path`;

  if (route.kind === "event-stream") {
    return `export function ${route.id}(
  apiBaseUrl: string,
  ${leadingPathArguments}${authParameter}signal?: AbortSignal
) {
  return fetch(apiUrl(apiBaseUrl, ${pathExpression}), {
    credentials: "include",
    headers: {
${authHeaderLine}      accept: "text/event-stream"
    },
    signal
  });
}
`;
  }

  if (route.kind === "stream") {
    if (route.method === "GET" && route.id === "streamAgentRunEvents") {
      return `export function ${route.id}(
  apiBaseUrl: string,
  ${leadingPathArguments}${authParameter}after = 0,
  signal?: AbortSignal
) {
  const query = after > 0 ? \`?after=\${encodeURIComponent(String(after))}\` : "";
  return fetch(\`\${apiUrl(apiBaseUrl, ${pathExpression})}\${query}\`, {
    credentials: "include",
    headers: {
${authHeaderLine}    },
    signal
  });
}
`;
    }
    return `export function ${route.id}(
  apiBaseUrl: string,
  ${leadingPathArguments}${authParameter}body: ${route.requestType},
  signal?: AbortSignal
) {
  return fetch(apiUrl(apiBaseUrl, ${pathExpression}), {
    method: ${JSON.stringify(route.method)},
    credentials: "include",
    headers: {
${authHeaderLine}      "content-type": "application/json"
    },
    body: JSON.stringify(body),
    signal
  });
}
`;
  }

  if (route.method === "GET") {
    return `export async function ${route.id}(
  apiBaseUrl: string,
  ${leadingPathArguments}${authParameter.trimEnd()}
) {
  const response = await fetch(apiUrl(apiBaseUrl, ${pathExpression}), {
    credentials: "include",
    headers: {
${authHeaderLine}
    }
  });

  if (!response.ok) {
    throw await apiError(${JSON.stringify(route.id)}, response);
  }

  return response.json() as Promise<${route.responseType}>;
}
`;
  }

  return `export async function ${route.id}(
  apiBaseUrl: string,
  ${leadingPathArguments}${authParameter}body: ${route.requestType}
) {
  const response = await fetch(apiUrl(apiBaseUrl, ${pathExpression}), {
    method: ${JSON.stringify(route.method)},
    credentials: "include",
    headers: {
${authHeaderLine}      "content-type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw await apiError(${JSON.stringify(route.id)}, response);
  }

  return response.json() as Promise<${route.responseType}>;
}
`;
}

const source = `// Generated by services/api/scripts/generate-client.ts.
// Do not edit by hand.

${apiSpec.types.trim()}

export const apiRoutes = ${JSON.stringify(routes, null, 2)} as const;

${routes
  .map(
    (route) =>
      `const ${routeConstantName(route.id)} = apiRoutes.find((route) => route.id === ${JSON.stringify(route.id)})!;`
  )
  .join("\n")}

export function resolveApiBaseUrl(apiBaseUrl: string) {
  return apiBaseUrl.trim().replace(/\\/+$/, "");
}

export function apiUrl(apiBaseUrl: string, path: string) {
  return \`\${resolveApiBaseUrl(apiBaseUrl)}\${path}\`;
}

export function routePath(path: string, params: Record<string, string>) {
  return path.replace(/:([A-Za-z0-9_]+)/g, (_match, key: string) => {
    const value = params[key];
    if (!value) {
      throw new Error(\`Missing API route parameter: \${key}\`);
    }

    return encodeURIComponent(value);
  });
}

export class ApiError extends Error {
  constructor(
    readonly routeId: string,
    readonly status: number,
    readonly details: string,
    message: string
  ) {
    super(message);
  }
}

async function apiError(routeId: string, response: Response) {
  const details = await response.text().catch(() => "");
  const message = parseErrorMessage(details);
  return new ApiError(
    routeId,
    response.status,
    details,
    \`\${routeId} failed with \${response.status}\${message ? \`: \${message}\` : ""}\`
  );
}

function parseErrorMessage(details: string) {
  if (!details) {
    return "";
  }

  try {
    const body = JSON.parse(details) as { error?: unknown; message?: unknown };
    if (typeof body.message === "string" && body.message) {
      return body.message;
    }

    if (typeof body.error === "string" && body.error) {
      return body.error;
    }
  } catch {
    return details;
  }

  return details;
}

function authorizationHeaders(sessionToken: string | undefined): Record<string, string> {
  return sessionToken ? { authorization: \`Bearer \${sessionToken}\` } : {};
}

${routes.map(functionSource).join("\n")}
`;

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, source);
console.log(`Generated ${outputPath}`);

function pathParams(path: string) {
  return Array.from(path.matchAll(/:([A-Za-z0-9_]+)/g), (match) => match[1]);
}
